// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {models} from '../models';

export function AddCamera(arg1:string,arg2:string):Promise<number>;

export function AddCameraToGo2rtc(arg1:number,arg2:string):Promise<void>;

export function AddZone(arg1:database.Zone):Promise<number>;

export function CountCameras():Promise<number>;

export function CountEvents():Promise<number>;

export function DeleteCamera(arg1:number):Promise<void>;

export function GenerateGo2rtcConfig(arg1:Array<database.Camera>):Promise<string>;

export function GetCameras():Promise<Array<database.Camera>>;

export function GetEventsByZone(arg1:number):Promise<Array<database.Event>>;

export function GetRTSPStreamURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetZonesByCamera(arg1:number):Promise<Array<database.Zone>>;

export function ScanNetwork():Promise<Array<models.DiscoveredCamera>>;

export function UpdateCamera(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateZone(arg1:database.Zone):Promise<void>;
