// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCamera(arg1, arg2) {
  return window['go']['main']['App']['AddCamera'](arg1, arg2);
}

export function AddCameraToGo2rtc(arg1, arg2) {
  return window['go']['main']['App']['AddCameraToGo2rtc'](arg1, arg2);
}

export function AddZone(arg1) {
  return window['go']['main']['App']['AddZone'](arg1);
}

export function GenerateGo2rtcConfig(arg1) {
  return window['go']['main']['App']['GenerateGo2rtcConfig'](arg1);
}

export function GetCameras() {
  return window['go']['main']['App']['GetCameras']();
}

export function GetEventsByZone(arg1) {
  return window['go']['main']['App']['GetEventsByZone'](arg1);
}

export function GetRTSPStreamURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRTSPStreamURL'](arg1, arg2, arg3);
}

export function GetZonesByCamera(arg1) {
  return window['go']['main']['App']['GetZonesByCamera'](arg1);
}

export function ScanNetwork() {
  return window['go']['main']['App']['ScanNetwork']();
}
